# Generated by Django 5.1.3 on 2024-11-20 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='updated_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
