# Generated by Django 5.1.3 on 2024-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calci', '0002_alter_ledger_updated_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
