# Generated by Django 5.1.3 on 2024-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calci', '0003_alter_ledger_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
